# zkill-mirror configuration
# the defaults are given but commented out
#
# everything that is set here can be overridden by environment variables
# the name should be ZKM_ followed by the uppercase setting, e.g.
# execute this in bash: ZKM_VERBOSE=true ZKM_PORT=7777 ./zkill-mirror serve
#

# port to listen on
# port = 8080

# url prefix
# url_prefix = "/"

# database configuration
#
# name of database file
# db_name = "zkill-mirror.bolt"
# disable sync for db files.  dangerous.  fast.
# db_nosync = false

# bobstorage configuration
#
# name of bobstorage directory
# bobs_name = "zkill-mirror.bobs"
#

# pulling of zkill data
#
# max duration to wait before polling zkillboard
# pull_delay = 5m
#
# pulling is enabled by default.
# pull_enabled = true

# cache templates
# cache_templates = true

# verbose output
# verbose = false

# default command: usually help, but for development with gin serve is better
# default_command = "help"
